#-*- coding:utf8 -*-

import os
import sys
import re
import string

###############################################################
############## CONFIGURATION ZONE #############################
## putting hands outside of this zone is just a YOUR PROBLEM ##
excluded=[]
image_formats=["jpg", "tiff", "png", "svg"]
############ END CONFIGURATION ZONE ###########################
###############################################################

fullbody_template=string.Template("""<html>
<head>
    <title>$path - Teca</title>
</head>
<body>
    $images
    <footer>Generated by teca.py, a python project brought to you by alfateam123</footer>
</body>
</html>""")



def filterImages(files):
     regex="\.("+"|".join(image_formats)+")$"
     return filter(lambda s: re.match(regex, s), files)

def generateIndex(path, files):
    #preparing the index
    index_file=open(os.path.join(path, "index.html"), "w")
    template_params={'path':path, 'images':''}

    #write the rest
    
    #closing the file and saving modifications
    index_file.write(fullbody_template.safe_substitute(template_params))
    index_file.close()

def goDeeper(starting_path):
    for root, dirs, files in os.walk(starting_path, topdown=True):
        #files[:]=filterImages(files)
        dirs[:]=[d for d in dirs if d not in excluded]
        
        generateIndex(root, files)

if __name__=="__main__":
    spath=sys.argv[-1]
    goDeeper(spath)
